---
title: "GJ Investor summit"
author: "Aman Malik"
date: "2024-03-01"
output:
  html_document:
    code_folding: hide
    toc: true
    number_sections: true
    toc_float: true
    theme: united
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F,cache = T)
```



```{r include=FALSE}
# Required packages
library(rgcam) # for getting data from database and reading it
library(tidyverse) # for manipulating data and making plots
library(jgcricolors) # color scheme from JGCRI
library(ggsci) # additional color palettes
library(ggthemes) # themese to make nice plots 
library(ggpubr) # additional themes to make nice plots
library(patchwork) # to put multiple plots together
library(ggrepel) # for geom label repel
#to install rgcam follow instructions:
#library(devtools)#devtools package should be installed for this to work
#devtools::install_github("JGCRI/rgcam",build_vignettes = TRUE,force = T)
library(jgcricolors)
```


```{r eval=FALSE, include=FALSE}
## Connecting to database and writing database output to a project file


# only needs to be run once or to add new scenarios to the project file
path <- 'D:/GCAM_State/output/' # change this path to where database is locally
conn <- localDBConn(path, 'database_basexdb')
queryFileInput <- 'queries.xml'
prj <- addScenario(conn, proj = 'GJNZ.dat', scenario =  c('BAU_GJ'), queryFile = queryFileInput,warn.empty = T,clobber = T) # This command runs queries from queryFileInput against the database, extract the results for two scenario called and write the results to a file called "GJNZ.dat". 
scenarios <- listScenarios(prj)# to check which scenarios have been installed
queries <- listQueries(prj)# to check all queries
                   
```

```{r}
prj <- mergeProjects("data/GJNZ_BAU_26June.dat","data/GJNZ_NZ70_26June.dat")

prj <- dropScenarios(prj,"Net_Zero")

queries <- listQueries(prj2)

#Renaming scenarios

# Loop through each dataframe in the list
for (i in seq_along(queries)) {
  # Access the dataframe
  prj[["NZ70_Trn_prcElas0.25"]][[queries[i]]][["scenario"]] <- "Net_Zero"
  
}

# prj <- dropScenarios(prj,"ElecRail_ElecShwt_NZ70")
# prj <- dropScenarios(prj,"NZ-Ind_GJ-2070_ROW-2080")

#names(prj) <- c("BAU","NZ_2070")


#prj <- rgcam::dropScenarios(prj2,scenarios = "NZ-Ind-2070_GJ-2050_ROW-2080")


```

# Socioeconomics
```{r}
gdp <- getQuery(prj,"GDP by region") %>% mutate(category="GDP")
pop <- getQuery(prj,"Population by region") %>% mutate(category="Pop")
gdpPc <- getQuery(prj,"PPP GDP by region") %>% mutate(category="GDPPC")

socioeco <- bind_rows(gdp,pop,gdpPc)# %>% filter(scenario=="BAU_GJ")

ggplot(socioeco %>% filter(region %in% c("GJ", "TN", "KA", "MH"), category == "Pop",year >2005,year<2075,scenario=="Reference"), mapping = aes(x = year, y = value / 1e3, color = region)) +
  geom_line(linewidth = 1.2) +
  geom_point(shape="circle",size=2)+
  geom_label_repel(socioeco %>% filter(region %in% c("GJ", "TN", "KA", "MH"), category == "Pop",year==2070,scenario=="Reference"), mapping = aes(x = year, y = value / 1e3, color = region,label = region),
    nudge_x = 6, box.padding = 0.3, direction = "y",
    na.rm = TRUE, show.legend = F,force_pull = 0.5)+
  geom_line() +  # Divide by 1e6 to convert to millions
  theme_pander(boxes = TRUE, base_size = 14) +
  scale_color_aaas() +
  scale_x_continuous(breaks = seq(2010, 2070, by = 10))+
      guides(color = "none")+
  labs(y = "Population (Millions)", x = "")


ggplot(socioeco %>% filter(region %in% c("GJ", "TN", "KA", "MH"), category == "GDPPC", year > 2005, year < 2075,scenario=="Reference"), 
       mapping = aes(x = year, y = value * 1000*1.98, color = region)) +
  geom_line(data = socioeco %>% filter(region %in% c("GJ", "TN", "KA", "MH"), category == "GDPPC", year > 2005, year <= 2020,scenario=="Reference"), 
            aes(x = year, y = value * 1000 * 1.98, color = region), 
            linetype = "solid", size = 1.2) +
  geom_point(shape="circle",size=2)+
  geom_line(data = socioeco %>% filter(region %in% c("GJ", "TN", "KA", "MH"), category == "GDPPC", year >= 2020, year < 2075,scenario=="Reference"), 
            aes(x = year, y = value * 1000*1.98, color = region), 
            linetype = "dashed", size = 1.2) +
   geom_label_repel(socioeco %>% filter(region %in% c("GJ", "TN", "KA", "MH"), category == "GDPPC",year==2070,scenario=="Reference"), mapping = aes(x = year, y = value*1000*1.98, color = region,label = region),
    nudge_x = 6, box.padding = 0.3, direction = "y",
    na.rm = TRUE, show.legend = F,force_pull = 0.5)+
  theme_pander(boxes = TRUE, base_size = 14) +
  scale_color_aaas() +
  scale_x_continuous(breaks = seq(2010, 2070, by = 10))+
      guides(color = "none")+
  labs(y = "GDP per capita (2020 USD)", x = "")

```


# Emissions
```{r}
emi <- getQuery(prj,query = 'CO2 emissions by aggregate sector') %>% 
      filter(region=="GJ",year >2010, year < 2075) %>% 
    mutate(sector=mgsub::mgsub( sector,pattern = c("biomass liquids","oil refining"),replacement = c("Industry","Industry"))) %>% 
  group_by(Units,scenario,region,sector,year) %>% 
  summarise(value=sum(value)) %>% 
  group_by(scenario, year) %>% 
  mutate(percent = value / sum(value), percent = percent * 100) %>% 
  ungroup()

annotate_data <- emi %>% 
  filter(year > 2005) %>%
  group_by(scenario, year) %>%
  summarize(total_value = sum(value * 3.67)) 

first_last_years <- annotate_data %>% 
  filter(year == min(year) | year == max(year))

##################################################
# Total emissions stacked area
ggplot()+
geom_area(data = emi %>% filter(year>2005),mapping=aes(x = year,y=value*3.67,fill=sector))+
  facet_wrap(~scenario)+
      theme_pubclean(base_size = 12)+
    scale_fill_viridis_d()+
  labs(y = expression(Emissions~(MTCO[2])),x="")+
   geom_label(data = first_last_years, 
             aes(x = year, y = total_value, label = round(total_value, 0)),
             vjust = -0.2, hjust = 0.5, size = 3, fill = "white", color = "black") 


ggsave("output_plots/emissions.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
##################################
#Individual emissions facet wrap
ggplot()+
geom_line(data = emi %>% filter(year>2015),mapping=aes(x = year,y=value*3.67,color=sector,linetype=scenario,group=interaction(sector,scenario)),size=1)+
  facet_wrap(~sector,scales = "free")+
  scale_x_continuous(breaks = seq(2020, 2070, by = 10))+
  guides(color = guide_legend(nrow = 2),linetype=guide_legend(nrow=2))+
  theme_pander(boxes = T,base_size = 14,lp = "top")+
  scale_fill_aaas()+
  labs(y="Emissions(MTCO2)",x="")+
  theme(axis.text.x = element_text(size = 8, angle = 45, vjust = 0.8, hjust = 0.8))
   # geom_label(data = first_last_years, 
   #           aes(x = year, y = total_value, label = round(total_value, 0)),
   #           vjust = -0.2, hjust = 0.5, size = 3, fill = "white", color = "black")

ggsave("output_plots/sector_emissions.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
######################
######################  
a <- ggplot(emi %>% filter(year == 2020),mapping = 
       aes(x = "", y = percent, fill = sector, group = scenario)) +
  geom_col(color = "white", size = 1) +
    facet_wrap(~scenario)+
  geom_text(aes(label = paste0(round(percent, 0), "%")),
            position = position_stack(vjust = 0.5),
            hjust = 1,  # Adjust hjust for label placement
            show.legend = FALSE) +
    theme_void() +
  scale_fill_aaas() +
  labs(title = "Emissions in 2020")



b <- ggplot(emi %>% filter(year == 2050),mapping = 
       aes(x = "", y = percent, fill = sector, group = scenario)) +
  geom_col(color = "white", size = 1) +
  facet_wrap(~scenario)+
  geom_text(aes(label = paste0(round(percent, 0), "%")),
            position = position_stack(vjust = 0.5),
            hjust = 1,  # Adjust hjust for label placement
            show.legend = FALSE) +
    theme_void() +
  scale_fill_aaas() +
  labs(title = "Emissions in 2050")

a+b + plot_layout(guides = "collect")

ggsave("output_plots/emissions_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

```

# Emission Intensity (MtCo2/GDP)
```{r}
tot_emissions <-  getQuery(prj,query = 'CO2 emissions by aggregate sector') %>% 
      filter(region=="GJ",year >2000, year < 2075,) %>% 
  group_by(scenario, year) %>% 
  mutate(percent = value / sum(value), percent = percent * 100) %>% 
  ungroup() %>% 
  group_by(scenario, year) %>%
  summarize(total_value = sum(value * 3.67)) 
#%>% 
 # filter(scenario=="Revised_NZ70")

gdp_gj <- getQuery(prj,"GDP by region") %>% mutate(category="GDP") %>% filter(region=="GJ",year > 2000)                                                         

ei <- left_join(tot_emissions,gdp_gj,by=c("year","scenario")) %>% 
  mutate(ei=total_value/value,year=as.factor(year))
```

# Emission intensity of Energy (MtCo2/EJ)
```{r}
fe3 <- getQuery(prj,"final energy consumption by aggregate sector and fuel") %>% 
  filter(region=="GJ") %>%
  mutate(sector=mgsub::mgsub( sector,pattern = c("Agriculture"),replacement = c("Industry"))) %>% 
  group_by(scenario,sector,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() 
  

emi <- getQuery(prj,query = 'CO2 emissions by aggregate sector') %>% 
      filter(region=="GJ",year >2010, year < 2075) %>% 
    mutate(sector=mgsub::mgsub( sector,pattern = c("biomass liquids","oil refining","IPPU"),replacement = c("Industry","Industry","Industry"))) %>% 
  group_by(Units,scenario,region,sector,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  mutate(value=value*3.67) %>% 
  select(-Units,-region)

energy_intensity <- left_join(fe3,emi,by=c("scenario","year","sector")) %>% filter(year>2010) %>% 
  mutate(eni=value.y/value.x)

writexl::write_xlsx(energy_intensity,"energy_intensity.xlsx")
energy_intensity <- readxl::read_excel("energy_intensity.xlsx")

#######################
ggplot()+
  geom_line(energy_intensity %>% filter(year>2015),mapping=aes(x=year,y=eni,linetype=scenario,color=sector))+
  theme_pander(boxes = T,base_size = 14)+
  scale_fill_aaas()+
  labs(y="Emission intensity of energy (MtCO2/EJ)",x="")

ggsave("output_plots/emission_intensity_of_energy.png",
  device = "png", dpi = "print",
  width = 7, height = 5
)
####################
```

# Energy intensity of GDP

```{r}
gdp_gj <- getQuery(prj,"GDP by region") %>% mutate(category="GDP") %>% filter(region=="GJ",year > 2010)      %>% 
  select(year,scenario,value) %>% 
  mutate(value=(value*1.98)/1000)

fe_tot <- getQuery(prj,"final energy consumption by aggregate sector and fuel") %>% 
  filter(region=="GJ",year>2010) %>%
  select(year,scenario,value) %>% 
group_by(year,scenario) %>% 
  summarise(value=sum(value)) 

enint_gdp <- left_join(fe_tot,gdp_gj,by=c("year","scenario")) %>% 
  mutate(enint_gdp=value.x/value.y)

writexl::write_xlsx(enint_gdp,"energy_intensity2.xlsx")
enint_gdp <- readxl::read_excel("energy_intensity2.xlsx")

#######################
ggplot()+
  geom_line(enint_gdp %>% filter(year>2015),mapping=aes(x=year,y=enint_gdp*1000,linetype=scenario))+
  theme_pander(boxes = T,base_size = 14)+
  scale_fill_aaas()+
  labs(y="Energy intensity of GDP (PJ/2020billion$)",x="")+
   scale_y_continuous(breaks = seq(0, 10, by = 1))

ggsave("output_plots/emission_intensity_of_energy.png",
  device = "png", dpi = "print",
  width = 7, height = 5
)
####################

```



# Electricity
```{r}
elec <- getQuery(prj,"final energy consumption by aggregate sector and fuel") %>% 
  filter(region=="GJ",input=="electricity") %>% 
  group_by(scenario,sector,year) %>% 
    summarise(value=sum(value)) %>% 
  group_by(year,scenario) %>% 
  mutate(percent=value/sum(value),percent=percent*100)



#writexl::write_xlsx(elec,"elec.xlsx")
elec <- read_xlsx("elec.xlsx") %>% select(-percent) %>% 
  group_by(year,scenario) %>% 
  mutate(percent=value/sum(value),percent=percent*100) %>% 
ungroup()

elec$scenario <- factor(elec$scenario, levels = c("Reference", "Net_Zero"))

#########################################
ggplot()+
geom_area(elec %>% filter(year>2015), mapping=aes(x=year, y=value*277.78, fill=sector))+
  facet_wrap(~scenario)+ 
       theme_pubclean(base_size = 12)+
    scale_fill_viridis_d()+
  labs(y="Electricity consumption (Billion Units)",x="")+
   scale_y_continuous(breaks = seq(0, 4500, by = 500))
  
ggsave("output_plots/elec_demand.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
#####################################
######################################
ggplot(elec %>% filter(year %in% c(2020, 2030, 2050, 2070)),mapping=aes(x=as.factor(year),y=percent,fill=sector))+
  geom_bar(stat = "identity")+
  facet_wrap(~scenario) +
  theme_minimal()+
  labs(y = "Sectoral share (%)", x = "Year")+
   scale_fill_viridis_d()+
  theme_pander() +
  geom_text(aes(label = ifelse(percent > 5, paste0(round(percent, 0), "%"), "")), 
            position = position_stack(vjust = 0.5), 
            size = 3) +
  coord_cartesian(ylim = c(0, 12))+labs(x="")

ggsave("output_plots/elec_demand_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

  
##################################

elec_gen <- getQuery(prj,"elec gen by subsector") %>% 
  filter(region=="GJ") %>% 
  group_by(scenario,year) %>% 
  mutate(percent=(value/sum(value))*100)

elec_gen$scenario <- factor(elec_gen$scenario,levels = c("Reference","Net_Zero"))

elec_gen_ren <- elec_gen %>% 
  filter(subsector %in% c("solar","wind","hydro","biomass")) %>% 
  select(-value) %>% 
  summarise(percent=sum(percent)) %>% 
  mutate(subsector="RE")

elec_gen_share <- elec_gen %>% select(-value,-output,-region) %>% 
  bind_rows(elec_gen_ren)

elec_gen_share$scenario <- factor(elec_gen_share$scenario, levels = c("Reference", "Net_Zero"))

elec_gen_share$subsector <- factor(elec_gen_share$subsector, levels = c("coal", "gas","solar","wind","hydro","nuclear","biomass","refined liquids","RE"))
  
elec_gen_tot <- elec_gen %>% 
  group_by(year,scenario) %>% 
  summarise(value=sum(value))

  
########################
ggplot()+
geom_area(elec_gen %>% filter(year>2010),mapping=aes(x=year,y=value*277.78,fill=subsector))+
  facet_wrap(~scenario) +
 theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Electricity Generation (Billion Units)",x="")+
 scale_y_continuous(breaks = seq(0,2500, by = 200))
  

ggsave("output_plots/elec_generation.png",
  device = "png", dpi = "print",
  width = 7, height = 5
)
###########################
  ggplot()+
  geom_line(elec_gen_share %>% filter(year>2015,subsector %in% c("coal","gas","solar","wind")), mapping=aes(x=year,y=percent,color=subsector,linetype=scenario,group=interaction(scenario,subsector)),size=1.2)+
  geom_line(elec_gen_share %>% filter(year>2015,subsector=="RE"), mapping=aes(x=year,y=percent,linetype=scenario,color=subsector,group=interaction(scenario,subsector)),size=0.5)+
  
  
  #facet_wrap(~scenario) +
  labs(y = "Share of power generation (%)", x = "Year")+
 theme_pubclean(base_size = 14)+
    scale_color_viridis_d()+
  theme(legend.position = "top",
        #axis.text.x = element_text(size = 9, angle = 45, vjust = 0.8, hjust = 0.8)
        )+
guides(color = guide_legend(nrow = 2),linetype=guide_legend(nrow=2))+
   coord_cartesian(ylim = c(0, 100))+labs(x="")+
  scale_x_continuous(breaks = seq(2020, max(elec_gen$year), by = 10)) 

# 
#   geom_text(aes(label = ifelse(percent > 5, paste0(round(percent, 0), "%"), "")), 
#             position = position_stack(vjust = 0.5), 
#             size = 3) +
#  

ggsave("output_plots/elec_generation_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

##################################

elec_cap <-  read_excel("data/RV-GJNZ Transport analysis.xlsx", 
    sheet = "Sheet1") %>% 
  pivot_longer(2:10,names_to = "subsector",values_to = "value")

elec_cap$scenario <- factor(elec_cap$scenario, levels = c("Reference", "Net_Zero"))
 ################

ggplot()+
  geom_col(elec_cap %>% filter(year!="2015-2020",subsector %in% c("solar PV","coal","wind onshore"),variable=="new"),mapping=aes(y=year,x=value,fill=scenario,group=interaction(subsector,scenario)),position = position_dodge())+
  facet_grid(~subsector,scales = "free")+
  theme_pubclean(base_size = 14,flip = T)+
    scale_fill_viridis_d(direction = -1)+
  labs(y="",x="Capacity addition (GW)")

ggsave("output_plots/elec_cap_addition.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
#################################
#########################
ggplot()+
geom_col(elec_cap %>% filter(year>2010,variable=="cumulative"),mapping=aes(x=value,y=year,fill=subsector))+
  facet_wrap(~scenario) +
 theme_pubclean(base_size = 14,flip = T)+
    scale_fill_viridis_d()+
  labs(x="Cumulative Capacity (GW)",y="")
 #scale_y_continuous(breaks = seq(0,2500, by = 200))


ggsave("output_plots/elec_cum_cap.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
##################
```


# Final Energy Consumption
```{r}
fe <- getQuery(prj,"final energy consumption by sector and fuel") %>% 
  filter(region=="GJ",sector!="cement") %>% 
  mutate(input=gsub(x = input,pattern="elect_td_res|elect_td_com",replacement="electricity")) %>% 
  group_by(scenario,input,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
 # mutate(scenario="BAU_GJ") %>% 
  group_by(year,scenario) %>% 
  mutate(percent=value/sum(value),percent=percent*100)

fe_tot <- fe %>% 
  select(-percent) %>% 
  group_by(year,scenario) %>% 
  summarise(value=sum(value))

fe$scenario <- factor(fe$scenario,levels = c("Reference","Net_Zero"))

##################################
ggplot()+
geom_area(fe %>% filter(year>2010,year<2075),mapping=aes(x=year,y=value,fill=input))+
  
  facet_wrap(~scenario) +
   theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Final Energy Consumption mix (EJ)",x="")+
scale_y_continuous(breaks = seq(0, 20, by = 2))+
  theme(legend.position = "top", 
        legend.box = "horizontal",
        legend.box.just = "center",
        legend.spacing.x = unit(0.5, 'cm'),
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 2))
  
ggsave("output_plots/final_energy_fuel_mix.png",
  device = "png", dpi = "print",
  width = 8, height = 5
)
###########################
###########################
ggplot(fe %>% filter(year %in% c(2020, 2050, 2070)),mapping=aes(x=as.factor(year),y=percent,fill=input))+
  geom_bar(stat = "identity")+
  facet_wrap(~scenario) +
  theme_minimal()+
  labs(y = "Share of fuels (%)", x = "Year")+
  theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  geom_text(aes(label = ifelse(percent > 5, paste0(round(percent, 0), "%"), "")), 
            position = position_stack(vjust = 0.5), 
            size = 3,color="white") +
  coord_cartesian(ylim = c(0, 100))+labs(x="")

ggsave("output_plots/final_energy_fuel_mix_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
###########################

fe3 <- getQuery(prj,"final energy consumption by aggregate sector and fuel") %>% 
  filter(region=="GJ") %>%
  group_by(scenario,sector,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,scenario) %>% 
  mutate(percent=value/sum(value),percent=percent*100)

fe3$scenario <- factor(fe3$scenario, levels = c("Reference", "Net_Zero"))

#########################
ggplot()+
geom_area(fe3 %>% filter(year>2010,year<2075),mapping=aes(x=year,y=value,fill=sector,group=sector))+
  facet_wrap(~scenario) +
  theme_pander(boxes = T,base_size = 14)+
  scale_fill_aaas()+
  labs(y="Final Energy Consumption by enduse (EJ)",x="")+
scale_y_continuous(breaks = seq(0, 20, by = 2))

ggsave("output_plots/final_energy_sector_mix.png",
  device = "png", dpi = "print",
  width = 7, height = 5
)
###########################

ggplot(fe3 %>% filter(year %in% c(2020, 2030, 2050, 2070)),mapping=aes(x=as.factor(year),y=percent,fill=sector))+
  geom_bar(stat = "identity")+
  facet_grid(~scenario)+
  theme_minimal()+
  labs(y = "Share of sector (%)", x = "Year")+
   scale_fill_aaas()+
  theme_pander() +
  geom_text(aes(label = ifelse(percent > 5, paste0(round(percent, 0), "%"), "")), 
            position = position_stack(vjust = 0.5), 
            size = 3) +
  coord_cartesian(ylim = c(0, 100))+labs(x="")

  ggsave("output_plots/final_energy_sector_mix_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
#################################
#################################
  
fe4 <- fe3 %>% 
  filter(year %in% c(2020,2070)) %>% select(-percent) %>% 
  pivot_wider(names_from = year,values_from = value) %>% 
  mutate(increase=`2070`/`2020`)

ggplot()+
  geom_col(fe4 %>% filter(scenario=="BAU"),mapping=aes(x=sector,y=increase,fill=sector))+scale_fill_aaas()+
  theme_pander()+
  labs(x="",y="Increase in demand (2070/2020")
  
 ggsave("output_plots/FE_demand_increase.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
#################################### 
```

# Transport
```{r}
trans <- getQuery(prj,query = "transport service output by mode") %>% 
  filter(region=="GJ") %>% 
  filter(!mode %in% c("LDV_2W","LDV_4W","LDV","road")) %>% 
  mutate(mode=mgsub::mgsub(mode,
  pattern = c("Air Domestic","Air International","Bus","HSR","LDV_3W","Passenger Rail","Cycle","Walk"),
                          replacement = c("Aviation","Aviation","Bus","Rail","3W","Rail","NMT","NMT"))) %>% 
  mutate(category=if_else(mode%in% c("2W","3W","4W","Aviation","Bus","NMT","Rail"),"Passenger","Freight")) %>% 
  group_by(scenario,year,mode,category) %>% 
    summarise(value=sum(value)) %>% 
  ungroup()  

trans_tot <- trans %>% 
  group_by(scenario,year,category) %>% 
  summarise(value=sum(value))


my_colors <- RColorBrewer::brewer.pal(11, "Set3")
names(my_colors) <- unique(trans$mode)

##########################
#Passenger and Freight
a <- ggplot()+
geom_area(trans %>% filter(year>2015,!mode %in% c("Ship Domestic","Ship International","Aviation"),scenario=="Reference"),mapping=aes(x=year,y=value/1000,fill=mode,group=interaction(mode,scenario)))+
  
  facet_wrap(~category,scales = "free") +
theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
   theme(axis.text.x = element_text(size = 8, angle = 45, vjust = 0.8, hjust = 0.8))+
  labs(y="Service Demand (billion tonne-km or billion pass-km)",x="")

ggsave("output_plots/transport_pass_freight_mode_demand.png",
  device = "png", dpi = "print",
  width = 8, height = 5
)
##########################
trans_share_pass <- trans %>%  
filter(category=="Passenger",!mode %in% c("Aviation")) %>% 
  group_by(year,scenario) %>% 
  mutate(share=value/sum(value),
         share=share*100)
##########################
b <- ggplot(trans_share_pass %>% filter(year %in% c(2020,2050,2070),scenario=="Reference"),mapping = 
       aes(x = "", y = share, fill = mode, group = scenario)) +
  geom_col(size = 1,show.legend = F) +
  facet_grid(~year)+
  geom_text(data = . %>% filter(share > 5),
    aes(label = paste0(round(share, 0), "%")),
            position = position_stack(vjust = 0.7),
            hjust = 0.5,  # Adjust hjust for label placement
              size=3,color="white")+
   theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  #scale_fill_manual(values = my_colors)+
  labs(y = "Passenger modal share",x="")
##########################

# b <- ggplot(trans_share_pass %>% filter(year == 2050),mapping = 
#        aes(x = "", y = share, fill = mode, group = interaction(scenario,year))) +
#   geom_col(color = "white", size = 1) +
#   geom_text(data = . %>% filter(share > 5),
#     aes(label = paste0(round(share, 0), "%")),
#             position = position_stack(vjust = 0.9),
#             hjust = 1,  # Adjust hjust for label placement
#             show.legend = FALSE) +
#     theme_void() +
#   scale_fill_ucscgb()+
#   labs(title = "Passenger modal share in 2050")

a+b + plot_layout(guides = "collect",widths = c(2,1))+plot_annotation(tag_levels = "a")&theme(legend.position = "top")

ggsave("output_plots/pass_transport_modal_share.png",
  device = "png", dpi = "print",
  width = 9, height = 6
)

############################

trans_fuel <- getQuery(prj,"transport final energy by fuel") %>% 
  filter(region=="GJ") %>% mutate(scenario=as.factor(scenario)) %>% 
  group_by(scenario,year) %>% 
  mutate(percentage=(value/sum(value))*100)

trans_fuel$scenario <- factor(trans_fuel$scenario, levels = c("Reference", "Net_Zero"))

ggplot()+
geom_area(trans_fuel %>% filter(year>2010,year<2075,input!= "hydrogen"),mapping=aes(x=year,y=value,fill=input,group=interaction(input)))+
  
  facet_wrap(~scenario) +
   theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Energy demand by fuel (EJ)",x="")+
  ylim(0,2.5)

ggsave("output_plots/transport_fuel.png",
  device = "png", dpi = "print",
  width = 8, height = 5
)

## Transport final energy by mode and fuel

trn_mode_fuel <- getQuery(prj,query = "transport final energy by mode and fuel") %>% 
  filter(region=="GJ")

trn_mode_fuel_share <- trn_mode_fuel %>% 
  group_by(scenario,year,mode) %>%
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,scenario) %>% 
  mutate(percentage=(value/sum(value))*100)


```

# Buildings
```{r}
build <- getQuery(prj,"building final energy by service (Cooking) and fuel") %>%   filter(region=="GJ",sector=="Cooking") %>% 
  group_by(scenario,input,year) %>% 
  summarise(value=sum(value))

##########################
ggplot()+
geom_area(build %>% filter(year>2010,year<2075),mapping=aes(x=year,y=value,fill=input))+
  facet_wrap(~scenario) +
  theme_pander(boxes = T,base_size = 14,lp = "bottom")+
  scale_fill_cosmic()+
  labs(y="Cooking energy demand (EJ)",x="")

ggsave("output_plots/BUILDING_cooking.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

##########################

build4 <- getQuery(prj,"building total final energy by aggregate service") %>% 
  filter(region=="GJ") %>% 
  group_by(year,scenario) %>% 
  mutate(percent=(value/sum(value))*100)
  
build4$scenario <- build4$scenario <- factor(build4$scenario, levels = c("Reference", "Net_Zero"))

build4_tot <- build4 %>% 
  group_by(scenario,year) %>% 
  summarise(value=sum(value))

#######################
ggplot()+
geom_area(build4 %>% filter(year>2015,sector!="Heating"),mapping=aes(x=year,y=value,fill=sector))+
  facet_wrap(~scenario) +
theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Energy Demand by Subsector (EJ)",x="")

ggsave("output_plots/BUILDING_subsector.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
###################################
#####################################
blah <- build4 %>% select(-percent) %>% 
  filter(year %in% c(2020,2070), scenario=="Reference", sector!="Heating") %>% 
  pivot_wider(names_from = year,values_from = value) %>% 
  mutate(increase=`2070`/`2020`) 

ggplot()+
  geom_col(blah, mapping=aes(x=sector, y=increase,fill=sector))+
  #facet_wrap(~sector)+
  theme_pander(boxes = T,base_size = 14,lp = "bottom")+
  scale_fill_tableau()+
  labs(y="increase (2070/2020)",x="")

ggsave("output_plots/energy_increase.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

#########################################

build6 <- getQuery(prj,"building final energy by fuel") %>% filter(region=="GJ") %>% 
  group_by(scenario,year) %>% 
  mutate(percent=(value/sum(value))*100)

build6$scenario <- factor(build6$scenario, levels = c("Reference", "Net_Zero"))

################################
ggplot()+
geom_area(build6 %>% filter(year>2015,input!="biomass"),mapping=aes(x=year,y=value,fill=input))+
  facet_wrap(~scenario) +
  theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Building energy demand by fuel (EJ)",x="")

ggsave("output_plots/BUILDING_fuel.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

###################################
###################################

ggplot(build6 %>% filter(year %in% c(2020, 2050, 2070)),mapping=aes(x=as.factor(year),y=percent,fill=input))+
  geom_bar(stat = "identity")+
  facet_wrap(~scenario) +
  theme_minimal()+
  labs(y = "Share of fuels (%)", x = "Year")+
   scale_fill_cosmic()+
  theme_pander() +
  geom_text(aes(label = ifelse(percent > 5, paste0(round(percent, 0), "%"), "")), 
            position = position_stack(vjust = 0.5), 
            size = 3,color="white") +
  coord_cartesian(ylim = c(0, 100))+labs(x="")

ggsave("output_plots/BUILDING_fuel_share.png",
  device = "png", dpi = "print",
  width = 7, height = 5
)

#######################################
floorspace <- getQuery(prj,"Building floorspace") %>% 
  filter(region=="GJ") %>%  group_by(scenario, building) %>%
  mutate(normalized_value = value / value[year == 2020])

ggplot(floorspace %>% filter(year>2015,year<2075),mapping=aes(x=year,y=normalized_value,color=building,group = building))+
  geom_line(size=1)+
 # geom_point(aes(x = min(year), y = 1), size = 3, shape = 16, color = "black") +  # Sphere at starting point
 # geom_point(aes(x = max(year), y = normalized_value), size = 3, shape = 16, color = "black") +  # Spheres at the end points
  
   scale_x_continuous(breaks = c(2020, 2070), labels = c("2020", "2070")) +
    theme_pander(boxes = T,base_size = 14,lp = "bottom")+
  scale_fill_cosmic()+labs(y="Increase in floorspace")

ggsave("output_plots/building_floorspace.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)

```


# Industry
```{r}
industry <- getQuery(prj,"final energy consumption by sector and fuel") %>% 
  filter(region=="GJ") %>% 
  filter(!str_detect(sector, "trn|resid|comm|fsuse")) %>% 
  group_by(scenario,input,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup() %>% 
  group_by(year,scenario) %>% 
   mutate(percent = value / sum(value), percent = percent * 100) %>% 
   ungroup()

industry_tot <- industry %>% 
  group_by(scenario,year) %>% 
  summarise(value=sum(value)) 


industry$scenario <- factor(industry$scenario, levels = c("Reference", "Net_Zero"))

ggplot()+
geom_area(industry %>% filter(year>2010),mapping=aes(x=year,y=value,fill=input))+
  facet_wrap(~scenario) +
  theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Industry energy demand by fuel (EJ)",x="")+
 #coord_cartesian(ylim = c(0, 12.5))+
     scale_y_continuous(breaks = seq(0, 12, by = 2))

  ggsave("output_plots/industry_fuel.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
#####################

ggplot(industry %>% filter(year %in% c(2020, 2050, 2070)),mapping=aes(x=as.factor(year),y=percent,fill=input))+
  geom_bar(stat = "identity")+
  facet_wrap(~scenario) +
  theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y = "Share of fuels (%)", x = "Year")+
  

  geom_text(aes(label = ifelse(percent > 5, paste0(round(percent, 0), "%"), "")), 
            position = position_stack(vjust = 0.5), 
            size = 3,color="white") +
  coord_cartesian(ylim = c(0, 100))+labs(x="")

ggsave("output_plots/industry_fuel_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)



a <- ggplot(industry %>% filter(year == 2020),mapping = 
       aes(x = "", y = percent, fill = input, group = scenario)) +
  geom_col(color = "white", size = 1) +
  facet_grid(~scenario)+
  geom_text(data = . %>% filter(percent > 3),
    aes(label = paste0(round(percent, 0), "%")),
            position = position_stack(vjust = 0.5),
            hjust = 1,  # Adjust hjust for label placement
            show.legend = FALSE,color="white") +
    theme_void() +
  scale_fill_cosmic() +
  labs(title = "Share in 2020")



b <- ggplot(industry %>% filter(year == 2070),mapping = 
       aes(x = "", y = percent, fill = input, group = scenario)) +
  geom_col(color = "white", size = 1) +
facet_grid(~scenario)+
  geom_text(data = . %>% filter(percent > 3),
    aes(label = paste0(round(percent, 0), "%")),
            position = position_stack(vjust = 0.5),
            hjust = 1,  # Adjust hjust for label placement
            show.legend = FALSE,color="white") +
    theme_void() +
  scale_fill_cosmic() +
  labs(title = "Share in 2070")

a+b + plot_layout(guides = "collect")

ggsave("output_plots/industry_fuel_share.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)


#################################


industry3 <- getQuery(prj,"final energy consumption by sector and fuel") %>% 
 filter(region=="GJ") %>% 
  filter(!str_detect(sector, "trn|resid|comm|_fsuse")) %>% 
  group_by(scenario,sector,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup()%>% mutate(scenario="BAU_GJ")


# industry4 <- getQuery(prj_powerAfter2025,"final energy consumption by sector and fuel") %>% 
#  filter(region=="GJ",year>2020) %>% 
#   filter(!str_detect(sector, "trn|resid|comm|_fsuse")) %>% 
#   group_by(scenario,sector,year) %>% 
#   summarise(value=sum(value)) %>% 
#   ungroup()
# 
# industry_sector_join <- bind_rows(industry3,industry4)%>% mutate(scenario="BAU_GJ")

ggplot()+
geom_area(industry3 %>% filter(year>2015),mapping=aes(x=year,y=value,fill=sector))+
  facet_wrap(~scenario) +
  theme_pander(boxes = T,base_size = 14,lp = "bottom")+
  scale_fill_ucscgb()+
  labs(y="Industry Final energy demand by energy use sector (EJ)",x="")

######################################3

industry5 <- getQuery(prj,"final energy consumption by sector and fuel") %>% 
 filter(region=="GJ") %>% 
  filter(!str_detect(sector, "trn|resid|comm|_enuse|process heat cement|cement")) %>% 
  group_by(scenario,sector,year) %>% 
  summarise(value=sum(value)) %>% 
  ungroup()

# 
# industry6 <- getQuery(prj_powerAfter2025,"final energy consumption by sector and fuel") %>% 
#  filter(region=="GJ",year>2020) %>% 
#   filter(!str_detect(sector, "trn|resid|comm|_enuse|process heat cement|cement")) %>% 
#   group_by(scenario,sector,year) %>% 
#   summarise(value=sum(value)) %>% 
#   ungroup()
# 
# industry_sector_join2 <- bind_rows(industry5,industry6)%>% mutate(scenario="BAU_GJ")

ggplot()+
geom_area(industry5 %>% filter(year>2010),mapping=aes(x=year,y=value,fill=sector))+
  facet_wrap(~scenario) +
  theme_pander(boxes = T,base_size = 14,lp = "bottom")+
  scale_fill_aaas()+
  labs(y="Industry Final energy demand by fuel (EJ)",x="")

```

# Agriculture

```{r}
agri <- getQuery(prj,"Agriculture final energy by service and fuel") %>% 
  filter(region=="GJ")

#writexl::write_xlsx(agri,"agri.xlsx")
agri <- read_excel("agri.xlsx")

agri_tot <- agri %>% 
  group_by(scenario,year) %>% 
  summarise(value=sum(value)) %>% 
  filter(year>2015)

##########################
ggplot()+
geom_area(agri %>% filter(year>2015,scenario=="Reference"),mapping=aes(x=year,y=value,fill=input))+
 # facet_wrap(~scenario) +
 theme_pubclean(base_size = 14)+
    scale_fill_viridis_d()+
  labs(y="Agricultural energy demand (EJ)",x="")

ggsave("output_plots/agri_demand.png",
  device = "png", dpi = "print",
  width = 8, height = 6
)
#############################
```

